### ISSUE TITLE
TypeDoc exiting with unexpected error: Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by arpu** [typedoc2md/typedoc-plugin-markdown#652]
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

Hi not sure why this crash, any idea how can debug this?
```
npm run devdocs                                    

> vrland@0.58.7 devdocs
> cross-env NODE_OPTIONS=--max_old_space_size=8192 typedoc --logLevel Verbose

[info] Loaded plugin typedoc-plugin-markdown
[debug] Reading tsconfig at ./tsconfig.json
[debug] Using TypeScript 5.5.3 from ./node_modules/typescript/lib
[debug] Expanded ./src/cap-uix-components/primitive/test.ts to:
	./src/cap-uix-components/primitive/test.ts
[debug] Converting with 1 programs 1 entry points
TypeDoc exiting with unexpected error:
Error: Debug Failure. False expression.
    at first (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:3063:9)
    at getSpecifierForModuleSymbol (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:55635:21)
    at serializeAsAlias (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:57675:87)
    at serializeSymbolWorker (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:57133:11)
    at serializeSymbol (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:56998:11)
    at /run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:56978:13
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:56977:67)
    at symbolTableToDeclarationStatements (/run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:56813:7)
    at /run/media/arpu/work/CAPTIC/projects/1.0/frontend_pr/node_modules/typescript/lib/typescript.js:54010:162
```

### TypeDoc configuration

{
  "compilerOptions": {
    "target": "es2019",
    "module": "es2020",
    "lib": ["es2020", "DOM", "DOM.Iterable"],
    "allowJs": true,
    "checkJs": false,
    "declaration": true,
    "emitDeclarationOnly": true,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": false,
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    // "jsxFragmentFactory": "preact.Fragment",
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "WelcomeComponent/*": ["src/instances/vrland.io/WelcomeComponent/*"],
      "Lobby": ["src/instances/vrland.io/Pages/Lobby/*"],
      "react": ["./node_modules/preact/compat/"],
      "react-dom": ["./node_modules/preact/compat/"],
      "react-dom/*": ["./node_modules/preact/compat/*"],
      "src": ["./src/"]
    }
  },
  "exclude": ["**/*.spec.ts", "node_modules", "public", "build"]
}
➜

**Comment by tgreyuk** [comment]
This looks like a typescript compiler error not related to this plugin.

**Comment by arpu** [comment]
Hey @tgreyuk  Thank You this fixed it!
